keys:
  - &jupiter age1pknfkunmqxpwfy7sv59qnz5d3wknfgw33tjkldp2up8znfrzuedsdkgvfz
  - &saturn age1nm553d4rh5hza5vkzq6g9w3jlkfz5g0czz0366p92gwgyrz7ldsqrm427w
  - &uranus age1jqyjprxdn3swn9afx5v3ckz04tun8t0f7kh36qeu69uqjlvg6ypq99lrux
  - &neptune age124a9emu6u3ajzfa590se7t279wvs09et5pqg58t9u3qm8qztm3ms800338

creation_rules:
  - path_regex: ^secrets/common\.yaml$
    key_groups:
      - age:
          - *jupiter
          - *saturn
          - *uranus
          - *neptune
